### ISSUE TITLE
INSTALL.md updates for macOS

### ISSUE THREAD

**Issue by jahndan** [pret/pokeplatinum#246]
I plan on resolving this issue with a PR soon, but am opening this to summarize what I've found so far and to ask a few questions.

I'm not sure how much detail I should add to the macOS section of `INSTALL.md`: should I explicitly write out the brew install commands with the dependencies if said dependencies vary based on the version of macOS? should I include instructions to configure PATH in zsh to shadow apple clang (and its aliases) with another compiler?

---

the command `realpath` doesn't exist on macOS Monterey or earlier (only available in /usr/bin from Ventura onwards)
- `brew install coreutils` fixes this (`/opt/homebrew/bin` needs to be on PATH)

subproject `knarc` does not build on apple clang 14.0.0 (Monterey) because it is not c++20 compliant (not sure if the version of apple clang bundled with xcode cmdline tools for Ventura/Sonoma is c++20 compliant enough to build `knarc`)
- any c++20 compliant compiler should work

apple clang is very annoying because it has unremovable aliases `gcc` and `g++`—meaning any other compiler masquerading as gcc (whether it's homebrew gcc or homebrew clang) must be earlier in path than `/usr/bin`, since meson looks for gcc/g++ first and will find one if apple clang is installed
- this isn't necessarily all that complicated to resolve with a symlink if you know what you're doing, but it's a lot of steps for an inexperienced user to follow

libpng can't build from source during configuration when it's not already already installed (for nitrogfx)
- `brew install pkg-config libpng` fixes this

also there's some configurations I can't currently test (if no one else gets around to it, I can probably test on macOS 13 by the end of the summer because I was planning on updating soon anyway)

---

_INSTALL.md_
> Mac OSX (<=10.14)

is this supposed to be for macOS Mojave and older? (if this works on those, i'll add a supplementary section for more recent versions instead of replacing this entirely)

---

**macOS 13 Ventura (and higher?)**
- it may be the case that xcode command line tools (plus the already listed dependencies) is enough
- `realpath` is apparently included in /usr/bin from here onwards (no coreutils)
- bundled compiler is a newer version of apple clang that *should* be c++20 compliant
- (needs verification) libpng may or may not build from source on Ventura when libpng and pkgconfig aren't already installed via brew

**macOS 12 Monterey (and lower?)**
- xclt is still necessary (homebrew prompts you to get it on install)
- it is technically possible to uninstall it after installing homebrew, but this solves nothing as `/usr/bin` contains wrapper binaries that prompt you to install xclt (which execute the real binaries in `/Library/Developer/CommandLineTools`) which includes gcc, g++, clang, etc. (which prompt xclt install or redirect to the actual clang executable) — so they still show up in PATH

**homebrew gcc-14 as c++20 compliant compiler**
- gcc-14/g++-14 will need symlinks with the names gcc/g++ for the current build system to find them instead of apple clang

**homebrew clang-18 as c++20 compliant compiler**
- clang-18 also needs symlinks with the names gcc/g++ for the current build system to find it instead of apple clang
- llvm clang is masquerading as gcc (which may not be a big deal because apple clang already does that)

---

**working configurations:**
- gcc in path is actually gcc-14 — pkg-config and libpng brewed
- gcc in path is actually clang-18 — pkg-config and libpng brewed

**failing configurations:**
- aliasing `gcc` to a compiler other than apple clang — meson ignores aliases
- earliest `gcc` in path is actually gcc-14 — subproject libpng doesn't build
- earliest `gcc` in path is actually clang-18 — subproject libpng doesn't build
- gcc-14 without gcc symlink — meson picks apple clang
- clang-18 without gcc symlink — meson picks apple clang

**configurations left to test:**
- something about CC and CXX environment variables? — fairly certain meson doesn't actually check this (but I don't know how to use them in the first place)
- cmake+libpng instead of pkgconfig+libpng

**Comment by mid-kid** [comment]
The CC and CXX variables are the de-facto way to pick a compiler. You can also use meson's `--native-file` option. https://mesonbuild.com/Cross-compilation.html

Still, I think it should be explored to downgrade the c++ standard requirements.

But, most importantly, are you sure you can run mwccarm.exe on your particular version of mac?
