### ISSUE TITLE
Decide on usage of Japanese NARC names vs English descriptors 

### ISSUE THREAD

**Issue by lhearachel** [pret/pokeplatinum#32]
Japanese names are required for the ROM to match, but references in code are always by index. This gives us some freedom to decide on whether to:

1. Use the Japanese names as-is and provide documentation describing their contents in English
2. Come up with English aliases for the indices for use in code

These aren't necessarily mutually exclusive options.

**Comment by lhearachel** [comment]
https://github.com/pret/pokeplatinum/pull/31

**Comment by wildfire248** [comment]
Preferences, in order:
1. English language enum, with docs. showing file path.
2. Japanese file path enum, with docs. on what each file is.
3. Two enums, one English descriptive and one based on the Japanese paths. (May be messy long term as any changes need to be applied to both enums correctly and may cause confusion if someone is seeing both versions of the same index.)

Regardless of which option we choose, full descriptions of each file would be good to have written down somewhere anyway.

**Comment by mid-kid** [comment]
Assuming an absence of additional tools to perform a relocation and the enum+array just being defined in code, I consider no other choice acceptable than using the real filenames in the enum.

The enum entries will only be used within the context of code that directly operates on it, making the context-specific documentation suffice to know what each file does. You're never going to encounter these enum fields in isolation.
