### ISSUE TITLE
Decide on how to compile NARCs in the build system

### ISSUE THREAD

**Issue by lhearachel** [pret/pokeplatinum#53]
We currently have a tool `csv2bin` which has an embedded NARC compilation process. This breaks separation of concerns principles. We should determine how to silo NARC compilation for data archives so that we have a single implementation of that compilation, letting our tools focus on building data files to be archived.

**Comment by lhearachel** [comment]
Noting that this is now also an issue with `json2bin`.

**Comment by Nomura-RH** [comment]
I thought about the options we have:

* keep `knarc`:
  * we make other tools invoke it, which is what `json2bin` currently does.
  * we separate the bin generation and narc generation steps. Will make meson files more verbose.
* ditch `knarc`, use `ndspy.NARC`:
  * we copy ndspy's NARC module in the folder of every "front-end" tool that calls json2bin (ugly) 
  * we embed ndspy's NARC module into `json2bin`'s folder, and pass front-end tools the path to said module

**Comment by mid-kid** [comment]
I should mention that requiring the use of a narc tool as a python module means you MUST write any narc-related tools in python. That is really inflexible especially when we can't predict how bad the performance of future python tools might turn out.
